-- CreateTable
CREATE TABLE `AccidentDetail` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `accidentId` INTEGER NOT NULL,
    `accidentNumber` VARCHAR(191) NULL,
    `year` INTEGER NULL,
    `month` INTEGER NULL,
    `day` INTEGER NULL,
    `hour` INTEGER NULL,
    `minute` INTEGER NULL,
    `occurredAtText` VARCHAR(191) NULL,
    `weekday` VARCHAR(191) NULL,
    `registrationStatus` VARCHAR(191) NULL,
    `registrationAgency` VARCHAR(191) NULL,
    `railwayDivision` VARCHAR(191) NULL,
    `accidentKind` VARCHAR(191) NULL,
    `railwayAccidentKind` VARCHAR(191) NULL,
    `primaryCause` VARCHAR(191) NULL,
    `primaryCauseOther` TEXT NULL,
    `secondaryCause` VARCHAR(191) NULL,
    `secondaryCauseOther` TEXT NULL,
    `rootCauseGroup` VARCHAR(191) NULL,
    `rootCause` VARCHAR(191) NULL,
    `rootCauseDetail` TEXT NULL,
    `riskSource` VARCHAR(191) NULL,
    `operationDisruptionType` VARCHAR(191) NULL,
    `riskIncidentDisruptionStatus` TEXT NULL,
    `riskIncidentDisruptionCause` TEXT NULL,
    `riskIncidentCauseDetail` TEXT NULL,
    `nearMissStatus` TEXT NULL,
    `nearMissCause` TEXT NULL,
    `nearMissDetail` TEXT NULL,
    `delayOperationStatus` TEXT NULL,
    `delayOperationCause` TEXT NULL,
    `delayOperationCauseDetail` TEXT NULL,
    `administrativeDistrict` VARCHAR(191) NULL,
    `facilityDamage` TEXT NULL,
    `totalCasualtyLabel` VARCHAR(191) NULL,
    `deaths` INTEGER NULL,
    `seriousInjuries` INTEGER NULL,
    `minorInjuries` INTEGER NULL,
    `totalDamageAmount` DECIMAL(18, 3) NULL,
    `casualtyCompensationAmount` DECIMAL(18, 3) NULL,
    `propertyDamageAmount` DECIMAL(18, 3) NULL,
    `otherDamageAmount` DECIMAL(18, 3) NULL,
    `humanLossCostTotal` DECIMAL(18, 3) NULL,
    `deathProductionLossCost` DECIMAL(18, 3) NULL,
    `deathMedicalCost` DECIMAL(18, 3) NULL,
    `deathAdministrativeCost` DECIMAL(18, 3) NULL,
    `deathPsychologicalCost` DECIMAL(18, 3) NULL,
    `seriousProductionLossCost` DECIMAL(18, 3) NULL,
    `seriousMedicalCost` DECIMAL(18, 3) NULL,
    `seriousAdministrativeCost` DECIMAL(18, 3) NULL,
    `seriousPsychologicalCost` DECIMAL(18, 3) NULL,
    `minorProductionLossCost` DECIMAL(18, 3) NULL,
    `minorMedicalCost` DECIMAL(18, 3) NULL,
    `minorAdministrativeCost` DECIMAL(18, 3) NULL,
    `minorPsychologicalCost` DECIMAL(18, 3) NULL,
    `materialDamageCostTotal` DECIMAL(18, 3) NULL,
    `vehicleRecoveryCost` DECIMAL(18, 3) NULL,
    `trackRecoveryCost` DECIMAL(18, 3) NULL,
    `signalRecoveryCost` DECIMAL(18, 3) NULL,
    `electricalRecoveryCost` DECIMAL(18, 3) NULL,
    `otherFacilityRecoveryCost` DECIMAL(18, 3) NULL,
    `facilityDamageCostTotal` DECIMAL(18, 3) NULL,
    `operationLossCostTotal` DECIMAL(18, 3) NULL,
    `delayLossCost` DECIMAL(18, 3) NULL,
    `substituteTransportCost` DECIMAL(18, 3) NULL,
    `fareRefundCost` DECIMAL(18, 3) NULL,
    `propertyEnvCompensationTotal` VARCHAR(191) NULL,
    `propertyPassengerCompensation` VARCHAR(191) NULL,
    `propertyStaffCompensation` VARCHAR(191) NULL,
    `propertyPublicCompensation` VARCHAR(191) NULL,
    `envPassengerCompensation` VARCHAR(191) NULL,
    `envStaffCompensation` VARCHAR(191) NULL,
    `envPublicCompensation` VARCHAR(191) NULL,
    `otherCostTotal` DECIMAL(18, 3) NULL,
    `investigationCost` DECIMAL(18, 3) NULL,
    `legalCost` DECIMAL(18, 3) NULL,
    `reputationCost` DECIMAL(18, 3) NULL,
    `otherMiscCost` DECIMAL(18, 3) NULL,
    `lineName` VARCHAR(191) NULL,
    `lineDirection` VARCHAR(191) NULL,
    `stationA` VARCHAR(191) NULL,
    `stationB` VARCHAR(191) NULL,
    `occurrencePlace` VARCHAR(191) NULL,
    `baseStation` VARCHAR(191) NULL,
    `accidentPointKm` DECIMAL(18, 3) NULL,
    `crossing` VARCHAR(191) NULL,
    `crossingType` VARCHAR(191) NULL,
    `guidePresent` VARCHAR(191) NULL,
    `trainType` VARCHAR(191) NULL,
    `trainNumber` VARCHAR(191) NULL,
    `consistNumber` VARCHAR(191) NULL,
    `vehicleNumber` VARCHAR(191) NULL,
    `vehicleAge` VARCHAR(191) NULL,
    `carCount` INTEGER NULL,
    `unitCount` INTEGER NULL,
    `operationFrom` VARCHAR(191) NULL,
    `operationTo` VARCHAR(191) NULL,
    `derailedCars` INTEGER NULL,
    `damagedCars` INTEGER NULL,
    `severeDamage` INTEGER NULL,
    `moderateDamage` INTEGER NULL,
    `minorDamage` INTEGER NULL,
    `totalDelayedTrains` INTEGER NULL,
    `highSpeedDelayedTrains` INTEGER NULL,
    `regularDelayedTrains` INTEGER NULL,
    `urbanDelayedTrains` INTEGER NULL,
    `dedicatedDelayedTrains` INTEGER NULL,
    `otherDelayedTrains` INTEGER NULL,
    `totalDelayMin` DECIMAL(18, 3) NULL,
    `totalDelayMax` DECIMAL(18, 3) NULL,
    `highSpeedDelayMin` DECIMAL(18, 3) NULL,
    `highSpeedDelayMax` DECIMAL(18, 3) NULL,
    `regularDelayMin` DECIMAL(18, 3) NULL,
    `regularDelayMax` DECIMAL(18, 3) NULL,
    `urbanDelayMin` DECIMAL(18, 3) NULL,
    `urbanDelayMax` DECIMAL(18, 3) NULL,
    `dedicatedDelayMin` DECIMAL(18, 3) NULL,
    `dedicatedDelayMax` DECIMAL(18, 3) NULL,
    `otherDelayMin` DECIMAL(18, 3) NULL,
    `otherDelayMax` DECIMAL(18, 3) NULL,
    `mainLineBlockTime` DECIMAL(18, 3) NULL,
    `mainLineRecoveryTime` DECIMAL(18, 3) NULL,
    `siteSituation` VARCHAR(191) NULL,
    `closingSetting` VARCHAR(191) NULL,
    `weatherStatus` VARCHAR(191) NULL,
    `temperature` DECIMAL(18, 3) NULL,
    `rainfall` DECIMAL(18, 3) NULL,
    `snowfall` DECIMAL(18, 3) NULL,
    `fogPresence` VARCHAR(191) NULL,
    `visibility` DECIMAL(18, 3) NULL,
    `earthquake` VARCHAR(191) NULL,
    `wind` DECIMAL(18, 3) NULL,
    `staffCategory` VARCHAR(191) NULL,
    `workCategory` VARCHAR(191) NULL,
    `relatedPersonCount` INTEGER NULL,
    `relatedPersonOrg` VARCHAR(191) NULL,
    `relatedPersonJob` VARCHAR(191) NULL,
    `relatedPersonRank` VARCHAR(191) NULL,
    `relatedPersonName` VARCHAR(191) NULL,
    `relatedPersonAge` INTEGER NULL,
    `placeTypeA` VARCHAR(191) NULL,
    `placeTypeB` VARCHAR(191) NULL,
    `operationLineCategory` VARCHAR(191) NULL,
    `trainVehicleCategory` VARCHAR(191) NULL,
    `speedLimit` DECIMAL(18, 3) NULL,
    `accidentSpeedA` DECIMAL(18, 3) NULL,
    `accidentSpeedB` DECIMAL(18, 3) NULL,
    `trackType` VARCHAR(191) NULL,
    `signalSystemType` VARCHAR(191) NULL,
    `crossingAccidentPlace` VARCHAR(191) NULL,
    `crossingAccidentVehicle` VARCHAR(191) NULL,
    `hazmatCause` VARCHAR(191) NULL,
    `hazmatType` VARCHAR(191) NULL,
    `safetyFacilityTrack` VARCHAR(191) NULL,
    `safetyFacilityVehicle` VARCHAR(191) NULL,
    `safetyFacilityCrossing` VARCHAR(191) NULL,
    `riskIncidentClass` VARCHAR(191) NULL,
    `riskIncidentAttribute` VARCHAR(191) NULL,
    `riskIncident` VARCHAR(191) NULL,
    `riskIncidentDetail` VARCHAR(191) NULL,
    `subjectParty` VARCHAR(191) NULL,
    `objectParty` VARCHAR(191) NULL,
    `place` VARCHAR(191) NULL,
    `status1` VARCHAR(191) NULL,
    `status2` VARCHAR(191) NULL,
    `riskAreaClass` VARCHAR(191) NULL,
    `riskArea` VARCHAR(191) NULL,
    `accidentOverview` TEXT NULL,
    `actionContent` TEXT NULL,
    `accidentCause` VARCHAR(191) NULL,
    `preventionPlan` TEXT NULL,
    `accidentNumberBackup` VARCHAR(191) NULL,
    `investigationStatus` VARCHAR(191) NULL,
    `registeredBy` VARCHAR(191) NULL,
    `savedAtText` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `AccidentDetail_accidentId_key`(`accidentId`),
    UNIQUE INDEX `AccidentDetail_accidentNumber_key`(`accidentNumber`),
    INDEX `AccidentDetail_lineName_idx`(`lineName`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `AccidentDetail` ADD CONSTRAINT `AccidentDetail_accidentId_fkey` FOREIGN KEY (`accidentId`) REFERENCES `RailwayAccident`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
