/** 사고 상세(공개) 화면 컬럼 그룹 — ACCIDENT_DB_COLUMNS key 기준 */
export const ACCIDENT_DETAIL_COLUMN_GROUPS = [
  {
    id: "accident",
    title: "사고정보",
    keys: [
      "accidentNumber",
      "year",
      "month",
      "day",
      "hour",
      "minute",
      "occurredAtText",
      "weekday",
      "registrationStatus",
      "registrationAgency",
      "railwayDivision",
      "accidentKind",
      "railwayAccidentKind",
      "primaryCause",
      "primaryCauseOther",
      "secondaryCause",
      "secondaryCauseOther",
      "rootCauseGroup",
      "rootCause",
      "rootCauseDetail",
      "riskSource",
      "operationDisruptionType",
      "riskIncidentDisruptionStatus",
      "riskIncidentDisruptionCause",
      "riskIncidentCauseDetail",
      "nearMissStatus",
      "nearMissCause",
      "nearMissDetail",
      "delayOperationStatus",
      "delayOperationCause",
      "delayOperationCauseDetail",
      "administrativeDistrict",
      "facilityDamage",
      "investigationStatus",
      "accidentOverview",
      "actionContent",
      "accidentCause",
      "preventionPlan",
    ],
  },
  {
    id: "casualty",
    title: "피해·인명",
    keys: [
      "totalCasualtyLabel",
      "deaths",
      "seriousInjuries",
      "minorInjuries",
      "totalDamageAmount",
      "casualtyCompensationAmount",
      "propertyDamageAmount",
      "otherDamageAmount",
    ],
  },
  {
    id: "cost",
    title: "비용·손실",
    keys: [
      "humanLossCostTotal",
      "deathProductionLossCost",
      "deathMedicalCost",
      "deathAdministrativeCost",
      "deathPsychologicalCost",
      "seriousProductionLossCost",
      "seriousMedicalCost",
      "seriousAdministrativeCost",
      "seriousPsychologicalCost",
      "minorProductionLossCost",
      "minorMedicalCost",
      "minorAdministrativeCost",
      "minorPsychologicalCost",
      "materialDamageCostTotal",
      "vehicleRecoveryCost",
      "trackRecoveryCost",
      "signalRecoveryCost",
      "electricalRecoveryCost",
      "otherFacilityRecoveryCost",
      "facilityDamageCostTotal",
      "operationLossCostTotal",
      "delayLossCost",
      "substituteTransportCost",
      "fareRefundCost",
      "propertyEnvCompensationTotal",
      "propertyPassengerCompensation",
      "propertyStaffCompensation",
      "propertyPublicCompensation",
      "envPassengerCompensation",
      "envStaffCompensation",
      "envPublicCompensation",
      "otherCostTotal",
      "investigationCost",
      "legalCost",
      "reputationCost",
      "otherMiscCost",
    ],
  },
  {
    id: "line",
    title: "노선·장소",
    keys: [
      "lineName",
      "lineDirection",
      "stationA",
      "stationB",
      "occurrencePlace",
      "baseStation",
      "accidentPointKm",
      "crossing",
      "crossingType",
      "guidePresent",
      "placeTypeA",
      "placeTypeB",
      "operationLineCategory",
      "place",
    ],
  },
  {
    id: "train",
    title: "열차정보",
    keys: [
      "trainType",
      "trainNumber",
      "consistNumber",
      "vehicleNumber",
      "vehicleAge",
      "carCount",
      "unitCount",
      "operationFrom",
      "operationTo",
      "derailedCars",
      "damagedCars",
      "severeDamage",
      "moderateDamage",
      "minorDamage",
      "trainVehicleCategory",
      "speedLimit",
      "accidentSpeedA",
      "accidentSpeedB",
      "trackType",
      "signalSystemType",
    ],
  },
  {
    id: "delay",
    title: "운행·지연",
    keys: [
      "totalDelayedTrains",
      "highSpeedDelayedTrains",
      "regularDelayedTrains",
      "urbanDelayedTrains",
      "dedicatedDelayedTrains",
      "otherDelayedTrains",
      "totalDelayMin",
      "totalDelayMax",
      "highSpeedDelayMin",
      "highSpeedDelayMax",
      "regularDelayMin",
      "regularDelayMax",
      "urbanDelayMin",
      "urbanDelayMax",
      "dedicatedDelayMin",
      "dedicatedDelayMax",
      "otherDelayMin",
      "otherDelayMax",
      "mainLineBlockTime",
      "mainLineRecoveryTime",
    ],
  },
  {
    id: "site",
    title: "현장·기상",
    keys: [
      "siteSituation",
      "closingSetting",
      "weatherStatus",
      "temperature",
      "rainfall",
      "snowfall",
      "fogPresence",
      "visibility",
      "earthquake",
      "wind",
    ],
  },
  {
    id: "risk",
    title: "위험·안전",
    keys: [
      "crossingAccidentPlace",
      "crossingAccidentVehicle",
      "hazmatCause",
      "hazmatType",
      "safetyFacilityTrack",
      "safetyFacilityVehicle",
      "safetyFacilityCrossing",
      "riskIncidentClass",
      "riskIncidentAttribute",
      "riskIncident",
      "riskIncidentDetail",
      "subjectParty",
      "objectParty",
      "status1",
      "status2",
      "riskAreaClass",
      "riskArea",
    ],
  },
  {
    id: "staff",
    title: "관계자",
    keys: [
      "staffCategory",
      "workCategory",
      "relatedPersonCount",
      "relatedPersonOrg",
      "relatedPersonJob",
      "relatedPersonRank",
      "relatedPersonName",
      "relatedPersonAge",
    ],
  },
  {
    id: "system",
    title: "시스템·등록",
    keys: ["accidentNumberBackup", "registeredBy", "savedAtText"],
  },
  {
    id: "review",
    title: "보완검토",
    keys: [
      "supplementRequestStatus",
      "supplementRequestDetail",
      "supplementResultStatus",
      "supplementResultDetail",
    ],
  },
] as const;

export const ALL_ACCIDENT_DETAIL_COLUMN_KEYS = ACCIDENT_DETAIL_COLUMN_GROUPS.flatMap((g) => g.keys);

export function getApprovedGroupTitles(visibleKeys: Set<string>): string[] {
  return ACCIDENT_DETAIL_COLUMN_GROUPS.filter((group) =>
    group.keys.some((key) => visibleKeys.has(key)),
  ).map((group) => group.title);
}
