-- AlterTable
ALTER TABLE `SelfReportCase` MODIFY `status` ENUM('RECEIVED', 'ADMIN_ASSIGNED', 'TIER1_PROCESSING', 'TIER2_PROCESSING', 'TRANSFERRED', 'COMPLETED', 'CLOSED', 'UNPROCESSABLE', 'RETURNED_TO_ADMIN') NOT NULL DEFAULT 'RECEIVED';

ALTER TABLE `SelfReportCase` ADD COLUMN `intakeDecision` ENUM('PROCESS', 'UNPROCESSABLE', 'RETURN_TO_ADMIN', 'ALREADY_COMPLETED') NULL,
    ADD COLUMN `priorCompletionDate` DATETIME(3) NULL,
    ADD COLUMN `priorCompletionContent` TEXT NULL;

ALTER TABLE `SelfReportAttachment` MODIFY `kind` ENUM('CASE', 'RESULT', 'PRIOR_COMPLETION') NOT NULL DEFAULT 'CASE';
