-- AlterTable
ALTER TABLE `SelfReportCase` MODIFY `status` ENUM('RECEIVED', 'ADMIN_ASSIGNED', 'TIER1_PROCESSING', 'TIER2_ASSIGNMENT', 'TIER2_PROCESSING', 'TRANSFERRED', 'COMPLETED', 'CLOSED', 'UNPROCESSABLE', 'RETURNED_TO_ADMIN') NOT NULL DEFAULT 'RECEIVED';

ALTER TABLE `SelfReportCase` ADD COLUMN `processingPath` ENUM('TIER2_ASSIGN', 'DIRECT_INPUT') NULL;
