-- AlterTable
ALTER TABLE `SelfReportCase` ADD COLUMN `unprocessableReason` TEXT NULL,
    ADD COLUMN `unprocessableTier1StaffId` INTEGER NULL;

-- AlterTable
ALTER TABLE `SelfReportCase` MODIFY `status` ENUM('RECEIVED', 'ADMIN_ASSIGNED', 'TIER1_PROCESSING', 'TIER2_ASSIGNMENT', 'TIER2_PROCESSING', 'TRANSFERRED', 'COMPLETED', 'CLOSED', 'UNPROCESSABLE', 'UNPROCESSABLE_PENDING', 'RETURNED_TO_ADMIN') NOT NULL DEFAULT 'RECEIVED';

-- AddForeignKey
ALTER TABLE `SelfReportCase` ADD CONSTRAINT `SelfReportCase_unprocessableTier1StaffId_fkey` FOREIGN KEY (`unprocessableTier1StaffId`) REFERENCES `SelfReportStaff`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
